#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SHE_CFM_KPT")]
	public partial class CfmDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_R_MENU(TBL_R_MENU instance);
    partial void UpdateTBL_R_MENU(TBL_R_MENU instance);
    partial void DeleteTBL_R_MENU(TBL_R_MENU instance);
    partial void InsertTBL_M_ROLE(TBL_M_ROLE instance);
    partial void UpdateTBL_M_ROLE(TBL_M_ROLE instance);
    partial void DeleteTBL_M_ROLE(TBL_M_ROLE instance);
    partial void InsertTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void UpdateTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void DeleteTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void InsertTBL_M_USER(TBL_M_USER instance);
    partial void UpdateTBL_M_USER(TBL_M_USER instance);
    partial void DeleteTBL_M_USER(TBL_M_USER instance);
    partial void InsertTBL_T_APPROVAL(TBL_T_APPROVAL instance);
    partial void UpdateTBL_T_APPROVAL(TBL_T_APPROVAL instance);
    partial void DeleteTBL_T_APPROVAL(TBL_T_APPROVAL instance);
    partial void InsertTBL_M_STATUS_CFM(TBL_M_STATUS_CFM instance);
    partial void UpdateTBL_M_STATUS_CFM(TBL_M_STATUS_CFM instance);
    partial void DeleteTBL_M_STATUS_CFM(TBL_M_STATUS_CFM instance);
    #endregion
		
		public CfmDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_SHE_CFM_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CfmDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfmDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfmDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfmDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_R_MENU> TBL_R_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_ROLE> TBL_M_ROLEs
		{
			get
			{
				return this.GetTable<TBL_M_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MASTER_KARYAWAN_ALL> TBL_R_MASTER_KARYAWAN_ALLs
		{
			get
			{
				return this.GetTable<TBL_R_MASTER_KARYAWAN_ALL>();
			}
		}
		
		public System.Data.Linq.Table<VW_KARYAWAN_ALL> VW_KARYAWAN_ALLs
		{
			get
			{
				return this.GetTable<VW_KARYAWAN_ALL>();
			}
		}
		
		public System.Data.Linq.Table<VW_User> VW_Users
		{
			get
			{
				return this.GetTable<VW_User>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_MENU> VW_R_MENUs
		{
			get
			{
				return this.GetTable<VW_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_DISTRICT> VW_DISTRICTs
		{
			get
			{
				return this.GetTable<VW_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<VW_LOCATION> VW_LOCATIONs
		{
			get
			{
				return this.GetTable<VW_LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_SUB_MENU> TBL_R_SUB_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_SUB_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER> TBL_M_USERs
		{
			get
			{
				return this.GetTable<TBL_M_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_CFC> TBL_T_CFCs
		{
			get
			{
				return this.GetTable<TBL_T_CFC>();
			}
		}
		
		public System.Data.Linq.Table<VW_T_APPROVAL> VW_T_APPROVALs
		{
			get
			{
				return this.GetTable<VW_T_APPROVAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_APPROVAL> TBL_T_APPROVALs
		{
			get
			{
				return this.GetTable<TBL_T_APPROVAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_STATUS_CFM> TBL_M_STATUS_CFMs
		{
			get
			{
				return this.GetTable<TBL_M_STATUS_CFM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MENU")]
	public partial class TBL_R_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnName_MenuChanging(string value);
    partial void OnName_MenuChanged();
    partial void OnSub_MenuChanging(System.Nullable<int> value);
    partial void OnSub_MenuChanged();
    partial void OnIcon_MenuChanging(string value);
    partial void OnIcon_MenuChanged();
    partial void OnLink_MenuChanging(string value);
    partial void OnLink_MenuChanged();
    partial void OnOrderChanging(System.Nullable<int> value);
    partial void OnOrderChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this.OnName_MenuChanging(value);
					this.SendPropertyChanging();
					this._Name_Menu = value;
					this.SendPropertyChanged("Name_Menu");
					this.OnName_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this.OnSub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu = value;
					this.SendPropertyChanged("Sub_Menu");
					this.OnSub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this.OnIcon_MenuChanging(value);
					this.SendPropertyChanging();
					this._Icon_Menu = value;
					this.SendPropertyChanged("Icon_Menu");
					this.OnIcon_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this.OnLink_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Menu = value;
					this.SendPropertyChanged("Link_Menu");
					this.OnLink_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_ROLE")]
	public partial class TBL_M_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RoleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public TBL_M_ROLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MASTER_KARYAWAN_ALL")]
	public partial class TBL_R_MASTER_KARYAWAN_ALL
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _EMP_STATUS;
		
		private string _GENDER_CODE;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _EMAIL;
		
		private string _ACTIVE_STATUS;
		
		public TBL_R_MASTER_KARYAWAN_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KARYAWAN_ALL")]
	public partial class VW_KARYAWAN_ALL
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _EMP_STATUS;
		
		private string _GENDER_CODE;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _EMAIL;
		
		private string _ACTIVE_STATUS;
		
		public VW_KARYAWAN_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_User")]
	public partial class VW_User
	{
		
		private int _ID_Role;
		
		private string _Username;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DSTRCT_CODE;
		
		private string _RoleName;
		
		public VW_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL")]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this._ID_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_MENU")]
	public partial class VW_R_MENU
	{
		
		private int _ID;
		
		private string _RoleName;
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		public VW_R_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this._Sub_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this._Icon_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this._Link_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this._Order = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DISTRICT")]
	public partial class VW_DISTRICT
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		public VW_DISTRICT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(100)")]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this._DSTRCT_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LOCATION")]
	public partial class VW_LOCATION
	{
		
		private string _TABLE_CODE;
		
		private string _TABLE_DESC;
		
		public VW_LOCATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CODE", DbType="Char(18) NOT NULL", CanBeNull=false)]
		public string TABLE_CODE
		{
			get
			{
				return this._TABLE_CODE;
			}
			set
			{
				if ((this._TABLE_CODE != value))
				{
					this._TABLE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_DESC", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string TABLE_DESC
		{
			get
			{
				return this._TABLE_DESC;
			}
			set
			{
				if ((this._TABLE_DESC != value))
				{
					this._TABLE_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_SUB_MENU")]
	public partial class TBL_R_SUB_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Sub_Menu;
		
		private System.Nullable<int> _ID_Menu;
		
		private string _Sub_Menu_Description;
		
		private string _Link_Sub_Menu;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Sub_MenuChanging(int value);
    partial void OnID_Sub_MenuChanged();
    partial void OnID_MenuChanging(System.Nullable<int> value);
    partial void OnID_MenuChanged();
    partial void OnSub_Menu_DescriptionChanging(string value);
    partial void OnSub_Menu_DescriptionChanged();
    partial void OnLink_Sub_MenuChanging(string value);
    partial void OnLink_Sub_MenuChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_SUB_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sub_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Sub_Menu
		{
			get
			{
				return this._ID_Sub_Menu;
			}
			set
			{
				if ((this._ID_Sub_Menu != value))
				{
					this.OnID_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Sub_Menu = value;
					this.SendPropertyChanged("ID_Sub_Menu");
					this.OnID_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int")]
		public System.Nullable<int> ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu_Description", DbType="NVarChar(150)")]
		public string Sub_Menu_Description
		{
			get
			{
				return this._Sub_Menu_Description;
			}
			set
			{
				if ((this._Sub_Menu_Description != value))
				{
					this.OnSub_Menu_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu_Description = value;
					this.SendPropertyChanged("Sub_Menu_Description");
					this.OnSub_Menu_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Sub_Menu", DbType="NVarChar(250)")]
		public string Link_Sub_Menu
		{
			get
			{
				return this._Link_Sub_Menu;
			}
			set
			{
				if ((this._Link_Sub_Menu != value))
				{
					this.OnLink_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Sub_Menu = value;
					this.SendPropertyChanged("Link_Sub_Menu");
					this.OnLink_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER")]
	public partial class TBL_M_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Role;
		
		private string _Username;
		
		private System.Nullable<System.DateTime> _DateAdd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnDateAddChanging(System.Nullable<System.DateTime> value);
    partial void OnDateAddChanged();
    #endregion
		
		public TBL_M_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdd", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdd
		{
			get
			{
				return this._DateAdd;
			}
			set
			{
				if ((this._DateAdd != value))
				{
					this.OnDateAddChanging(value);
					this.SendPropertyChanging();
					this._DateAdd = value;
					this.SendPropertyChanged("DateAdd");
					this.OnDateAddChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_CFC")]
	public partial class TBL_T_CFC
	{
		
		private int _ID_CFC;
		
		private System.DateTime _WAKTU_ABSEN;
		
		private string _NRP;
		
		private string _ID_CHAMBER;
		
		private System.Nullable<double> _OXYGEN_SATURATION;
		
		private System.Nullable<double> _HEART_RATE;
		
		private System.Nullable<double> _SYSTOLIC;
		
		private System.Nullable<double> _DIASTOLIC;
		
		private System.Nullable<double> _TEMPRATURE;
		
		private string _FACE_PICTURE_URL;
		
		private System.Nullable<int> _ID_STATUS;
		
		private string _NOTE;
		
		private string _ATTENDANCE_NOTE;
		
		public TBL_T_CFC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CFC", DbType="Int NOT NULL")]
		public int ID_CFC
		{
			get
			{
				return this._ID_CFC;
			}
			set
			{
				if ((this._ID_CFC != value))
				{
					this._ID_CFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAKTU_ABSEN", DbType="DateTime NOT NULL")]
		public System.DateTime WAKTU_ABSEN
		{
			get
			{
				return this._WAKTU_ABSEN;
			}
			set
			{
				if ((this._WAKTU_ABSEN != value))
				{
					this._WAKTU_ABSEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHAMBER", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ID_CHAMBER
		{
			get
			{
				return this._ID_CHAMBER;
			}
			set
			{
				if ((this._ID_CHAMBER != value))
				{
					this._ID_CHAMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OXYGEN_SATURATION", DbType="Float")]
		public System.Nullable<double> OXYGEN_SATURATION
		{
			get
			{
				return this._OXYGEN_SATURATION;
			}
			set
			{
				if ((this._OXYGEN_SATURATION != value))
				{
					this._OXYGEN_SATURATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEART_RATE", DbType="Float")]
		public System.Nullable<double> HEART_RATE
		{
			get
			{
				return this._HEART_RATE;
			}
			set
			{
				if ((this._HEART_RATE != value))
				{
					this._HEART_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTOLIC", DbType="Float")]
		public System.Nullable<double> SYSTOLIC
		{
			get
			{
				return this._SYSTOLIC;
			}
			set
			{
				if ((this._SYSTOLIC != value))
				{
					this._SYSTOLIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIASTOLIC", DbType="Float")]
		public System.Nullable<double> DIASTOLIC
		{
			get
			{
				return this._DIASTOLIC;
			}
			set
			{
				if ((this._DIASTOLIC != value))
				{
					this._DIASTOLIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPRATURE", DbType="Float")]
		public System.Nullable<double> TEMPRATURE
		{
			get
			{
				return this._TEMPRATURE;
			}
			set
			{
				if ((this._TEMPRATURE != value))
				{
					this._TEMPRATURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACE_PICTURE_URL", DbType="VarChar(128)")]
		public string FACE_PICTURE_URL
		{
			get
			{
				return this._FACE_PICTURE_URL;
			}
			set
			{
				if ((this._FACE_PICTURE_URL != value))
				{
					this._FACE_PICTURE_URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_STATUS", DbType="Int")]
		public System.Nullable<int> ID_STATUS
		{
			get
			{
				return this._ID_STATUS;
			}
			set
			{
				if ((this._ID_STATUS != value))
				{
					this._ID_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(128)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTENDANCE_NOTE", DbType="VarChar(128)")]
		public string ATTENDANCE_NOTE
		{
			get
			{
				return this._ATTENDANCE_NOTE;
			}
			set
			{
				if ((this._ATTENDANCE_NOTE != value))
				{
					this._ATTENDANCE_NOTE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_T_APPROVAL")]
	public partial class VW_T_APPROVAL
	{
		
		private int _APPROVAL_ID;
		
		private System.Nullable<int> _ID_CFC;
		
		private System.Nullable<int> _ID_STATUS;
		
		private string _ID_CHAMBER;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _ATASAN;
		
		private System.Nullable<System.DateTime> _DATE_FROM_CFC;
		
		private System.Nullable<int> _JUMLAH_APPROVAL_PERHARI;
		
		private string _EMAIL;
		
		private string _STATUS;
		
		private string _APPROVER;
		
		private System.Nullable<System.DateTime> _WAKTU_APPROVAL;
		
		private System.Nullable<System.DateTime> _WAKTU_ABSEN;
		
		private System.Nullable<double> _OXYGEN_SATURATION;
		
		private System.Nullable<double> _HEART_RATE;
		
		private System.Nullable<double> _SYSTOLIC;
		
		private System.Nullable<double> _DIASTOLIC;
		
		private System.Nullable<double> _TEMPRATURE;
		
		private string _FACE_PICTURE_URL;
		
		private string _NOTE;
		
		private string _ATTENDANCE_NOTE;
		
		public VW_T_APPROVAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ID", DbType="Int NOT NULL")]
		public int APPROVAL_ID
		{
			get
			{
				return this._APPROVAL_ID;
			}
			set
			{
				if ((this._APPROVAL_ID != value))
				{
					this._APPROVAL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CFC", DbType="Int")]
		public System.Nullable<int> ID_CFC
		{
			get
			{
				return this._ID_CFC;
			}
			set
			{
				if ((this._ID_CFC != value))
				{
					this._ID_CFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_STATUS", DbType="Int")]
		public System.Nullable<int> ID_STATUS
		{
			get
			{
				return this._ID_STATUS;
			}
			set
			{
				if ((this._ID_STATUS != value))
				{
					this._ID_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHAMBER", DbType="VarChar(32)")]
		public string ID_CHAMBER
		{
			get
			{
				return this._ID_CHAMBER;
			}
			set
			{
				if ((this._ID_CHAMBER != value))
				{
					this._ID_CHAMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATASAN", DbType="VarChar(100)")]
		public string ATASAN
		{
			get
			{
				return this._ATASAN;
			}
			set
			{
				if ((this._ATASAN != value))
				{
					this._ATASAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_FROM_CFC", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_FROM_CFC
		{
			get
			{
				return this._DATE_FROM_CFC;
			}
			set
			{
				if ((this._DATE_FROM_CFC != value))
				{
					this._DATE_FROM_CFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUMLAH_APPROVAL_PERHARI", DbType="Int")]
		public System.Nullable<int> JUMLAH_APPROVAL_PERHARI
		{
			get
			{
				return this._JUMLAH_APPROVAL_PERHARI;
			}
			set
			{
				if ((this._JUMLAH_APPROVAL_PERHARI != value))
				{
					this._JUMLAH_APPROVAL_PERHARI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(255)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVER", DbType="VarChar(50)")]
		public string APPROVER
		{
			get
			{
				return this._APPROVER;
			}
			set
			{
				if ((this._APPROVER != value))
				{
					this._APPROVER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAKTU_APPROVAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> WAKTU_APPROVAL
		{
			get
			{
				return this._WAKTU_APPROVAL;
			}
			set
			{
				if ((this._WAKTU_APPROVAL != value))
				{
					this._WAKTU_APPROVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAKTU_ABSEN", DbType="DateTime")]
		public System.Nullable<System.DateTime> WAKTU_ABSEN
		{
			get
			{
				return this._WAKTU_ABSEN;
			}
			set
			{
				if ((this._WAKTU_ABSEN != value))
				{
					this._WAKTU_ABSEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OXYGEN_SATURATION", DbType="Float")]
		public System.Nullable<double> OXYGEN_SATURATION
		{
			get
			{
				return this._OXYGEN_SATURATION;
			}
			set
			{
				if ((this._OXYGEN_SATURATION != value))
				{
					this._OXYGEN_SATURATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEART_RATE", DbType="Float")]
		public System.Nullable<double> HEART_RATE
		{
			get
			{
				return this._HEART_RATE;
			}
			set
			{
				if ((this._HEART_RATE != value))
				{
					this._HEART_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTOLIC", DbType="Float")]
		public System.Nullable<double> SYSTOLIC
		{
			get
			{
				return this._SYSTOLIC;
			}
			set
			{
				if ((this._SYSTOLIC != value))
				{
					this._SYSTOLIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIASTOLIC", DbType="Float")]
		public System.Nullable<double> DIASTOLIC
		{
			get
			{
				return this._DIASTOLIC;
			}
			set
			{
				if ((this._DIASTOLIC != value))
				{
					this._DIASTOLIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPRATURE", DbType="Float")]
		public System.Nullable<double> TEMPRATURE
		{
			get
			{
				return this._TEMPRATURE;
			}
			set
			{
				if ((this._TEMPRATURE != value))
				{
					this._TEMPRATURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACE_PICTURE_URL", DbType="VarChar(128)")]
		public string FACE_PICTURE_URL
		{
			get
			{
				return this._FACE_PICTURE_URL;
			}
			set
			{
				if ((this._FACE_PICTURE_URL != value))
				{
					this._FACE_PICTURE_URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(128)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTENDANCE_NOTE", DbType="VarChar(128)")]
		public string ATTENDANCE_NOTE
		{
			get
			{
				return this._ATTENDANCE_NOTE;
			}
			set
			{
				if ((this._ATTENDANCE_NOTE != value))
				{
					this._ATTENDANCE_NOTE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_APPROVAL")]
	public partial class TBL_T_APPROVAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APPROVAL_ID;
		
		private System.Nullable<int> _ID_CFC;
		
		private System.Nullable<int> _ID_STATUS;
		
		private string _NRP;
		
		private System.Nullable<System.DateTime> _DATE_FROM_CFC;
		
		private System.Nullable<int> _JUMLAH_APPROVAL_PERHARI;
		
		private string _APPROVER;
		
		private System.Nullable<System.DateTime> _WAKTU_APPROVAL;
		
		private string _NOTED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPPROVAL_IDChanging(int value);
    partial void OnAPPROVAL_IDChanged();
    partial void OnID_CFCChanging(System.Nullable<int> value);
    partial void OnID_CFCChanged();
    partial void OnID_STATUSChanging(System.Nullable<int> value);
    partial void OnID_STATUSChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnDATE_FROM_CFCChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_FROM_CFCChanged();
    partial void OnJUMLAH_APPROVAL_PERHARIChanging(System.Nullable<int> value);
    partial void OnJUMLAH_APPROVAL_PERHARIChanged();
    partial void OnAPPROVERChanging(string value);
    partial void OnAPPROVERChanged();
    partial void OnWAKTU_APPROVALChanging(System.Nullable<System.DateTime> value);
    partial void OnWAKTU_APPROVALChanged();
    partial void OnNOTEDChanging(string value);
    partial void OnNOTEDChanged();
    #endregion
		
		public TBL_T_APPROVAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APPROVAL_ID
		{
			get
			{
				return this._APPROVAL_ID;
			}
			set
			{
				if ((this._APPROVAL_ID != value))
				{
					this.OnAPPROVAL_IDChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_ID = value;
					this.SendPropertyChanged("APPROVAL_ID");
					this.OnAPPROVAL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CFC", DbType="Int")]
		public System.Nullable<int> ID_CFC
		{
			get
			{
				return this._ID_CFC;
			}
			set
			{
				if ((this._ID_CFC != value))
				{
					this.OnID_CFCChanging(value);
					this.SendPropertyChanging();
					this._ID_CFC = value;
					this.SendPropertyChanged("ID_CFC");
					this.OnID_CFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_STATUS", DbType="Int")]
		public System.Nullable<int> ID_STATUS
		{
			get
			{
				return this._ID_STATUS;
			}
			set
			{
				if ((this._ID_STATUS != value))
				{
					this.OnID_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ID_STATUS = value;
					this.SendPropertyChanged("ID_STATUS");
					this.OnID_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_FROM_CFC", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_FROM_CFC
		{
			get
			{
				return this._DATE_FROM_CFC;
			}
			set
			{
				if ((this._DATE_FROM_CFC != value))
				{
					this.OnDATE_FROM_CFCChanging(value);
					this.SendPropertyChanging();
					this._DATE_FROM_CFC = value;
					this.SendPropertyChanged("DATE_FROM_CFC");
					this.OnDATE_FROM_CFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUMLAH_APPROVAL_PERHARI", DbType="Int")]
		public System.Nullable<int> JUMLAH_APPROVAL_PERHARI
		{
			get
			{
				return this._JUMLAH_APPROVAL_PERHARI;
			}
			set
			{
				if ((this._JUMLAH_APPROVAL_PERHARI != value))
				{
					this.OnJUMLAH_APPROVAL_PERHARIChanging(value);
					this.SendPropertyChanging();
					this._JUMLAH_APPROVAL_PERHARI = value;
					this.SendPropertyChanged("JUMLAH_APPROVAL_PERHARI");
					this.OnJUMLAH_APPROVAL_PERHARIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVER", DbType="VarChar(50)")]
		public string APPROVER
		{
			get
			{
				return this._APPROVER;
			}
			set
			{
				if ((this._APPROVER != value))
				{
					this.OnAPPROVERChanging(value);
					this.SendPropertyChanging();
					this._APPROVER = value;
					this.SendPropertyChanged("APPROVER");
					this.OnAPPROVERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAKTU_APPROVAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> WAKTU_APPROVAL
		{
			get
			{
				return this._WAKTU_APPROVAL;
			}
			set
			{
				if ((this._WAKTU_APPROVAL != value))
				{
					this.OnWAKTU_APPROVALChanging(value);
					this.SendPropertyChanging();
					this._WAKTU_APPROVAL = value;
					this.SendPropertyChanged("WAKTU_APPROVAL");
					this.OnWAKTU_APPROVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTED", DbType="VarChar(MAX)")]
		public string NOTED
		{
			get
			{
				return this._NOTED;
			}
			set
			{
				if ((this._NOTED != value))
				{
					this.OnNOTEDChanging(value);
					this.SendPropertyChanging();
					this._NOTED = value;
					this.SendPropertyChanged("NOTED");
					this.OnNOTEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_STATUS_CFM")]
	public partial class TBL_M_STATUS_CFM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_STATUS;
		
		private string _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_STATUSChanging(int value);
    partial void OnID_STATUSChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_M_STATUS_CFM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_STATUS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_STATUS
		{
			get
			{
				return this._ID_STATUS;
			}
			set
			{
				if ((this._ID_STATUS != value))
				{
					this.OnID_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ID_STATUS = value;
					this.SendPropertyChanged("ID_STATUS");
					this.OnID_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(255)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
